export const LOAD_USER_START = "LOAD_USER_START";
export const LOAD_USER_SUCCESS = "LOAD_USER_SUCCESS";
export const LOAD_USER_FAIL = "LOAD_USER_FAIL";

export const SVAE_DISH = "SVAE_DISH";
export const SVAE_DISH_START = "SVAE_DISH_START";
export const LOGOUT_USER = "LOGOUT_USER";
